src/init.cpp

Tested and the game no longer crashes if the tooltip texts  in the miscellaneous menu are missing.

Creates the language array with empty strings to avoid crashing

---

src/actchest.cpp
src/maps.cpp

Added settable chest types through using editor sprites 75-81, so players can make maps with fixed reward categories and not use random chests. Random chests in map generation and the original editor icon still behave the same.
Sprites.txt needs to be modified to include 7 new lines for these icons, I just added 7 chests icons to the end:
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
images/sprites/chest.png
Updated to match latest master branch.

Chest types 0 to 7 to be set by new additional editor sprites

---

src/buttons.cpp
src/editor.cpp
src/editor.hpp
src/main.cpp
src/monster_automaton.cpp
src/monster_cockatrice.cpp
src/monster_crystalgolem.cpp
src/monster_demon.cpp
src/monster_ghoul.cpp
src/monster_goatman.cpp
src/monster_goblin.cpp
src/monster_incubus.cpp
src/monster_insectoid.cpp
src/monster_kobold.cpp
src/monster_scarab.cpp
src/monster_shadow.cpp
src/monster_troll.cpp
src/stat_shared.cpp

Fixed crash when duplicating editor sprite after deleting the previous.
Stopped clearing of monster stats when you edit one of it's items. Now stats should properly remain until they are saved inside the main window.

Fixed several monster naming, now can properly be set through editor.

---

src/init.cpp
src/items.cpp

This fixes compilation on more restrictive settings for gcc, which don't
like this insecure practice. Could also pass -Wno-error=format-insecure
or something like that, but actually solving the issue is always nicer!

Switch snprintf without params → strncpy

---

INSTALL.txt

INSTALL.txt only mentioned Fmod Ex as a sound library and didn't say anything about added OpenAL support, so I fixed it.

Included OpenAL support in INSTALL.txt

---

src/entity.cpp

This is an enhancement for when a Player takes damage from starvation.
The issue is that there is no screen shake or damage sound played when you take damage from starvation. This is an issue because every other source of damage causes the screen to shake and a sound clip to play.
This issue is fixed by adding in a screen shake and playing `Damage.ogg` using the same parameters as taking damage from poison.

[MASTER] Enhancement - Hunger damage plays sound and shakes screen

---

src/actmonster.cpp
src/magic/spell.cpp
src/maps.cpp
src/net.cpp
src/scores.cpp

- few small mem leaks on error return paths.
- possible overflow when number of players == MAXPLAYERS.
- a pointer freed too early leading to use after free.
- a boolean function not returning.

couple of small code corrections :

---

lang/en.txt
src/item_usage_funcs.cpp
src/magic/castSpell.cpp
src/magic/magic.cpp
src/maps.cpp

Fixes crashing for server, occurs when spray acid or drain soul is cast on a monster that is a "friend". Only when FF is disabled. Otherwise damages as normal.
Also spaced out the text scroll to stop it overlapping for most resolutions.

Beta hotfix for friendly fire OFF

---

src/net.cpp

This is a fix for #244.
The issue is that there was just a missing line of code to match the Host's code of setting the Client's MP to be 1/2 that of their max.

Fix Issue #244 - Client does not respawn with half MP

---

src/magic/actmagic.cpp

This is a fix for #251 and #249.
The issue is that there is a repeating set of code checking to see if Friendly Fire is turned off. This is a small refactor to extract that to before the alerting code, checking to see if equipment should be damaged when reflecting, and preventing allies from being set on fire.

Fix Issue #251 - Spells aggro friendlies with F.F. off and other fixes

---

src/entity.cpp

This is a fix for #220.
The issue is that there are no checks for if Buddha mode is enabled when processing damage from HUNGER effect.

Fix Issue #220 - Hungry Buddha Dies

---

src/entity.cpp

This is a fix for #258.
The issue is that there are no checks for if Buddha mode is on when dealing damage through the BURNING status effect.

Fix Issue #258 - Fire Kills Buddha

---

src/entity.cpp

This is a fix for #75.
The issue is that there is no check to prevent calling `monsterAddNearbyItemToInventory()` while the Monster is Asleep.

Fix Issue #75 - Monsters can equip Items while Asleep

---

src/game.cpp

This is a fix for #241.
The issue is that the Status Bar, which also draws Tooltips, executes before `drawMinimap()`. This simple rearrangement should be sufficient. Due to placing the `drawStatus()` call after a few other code blocks, there could be other side effects. This can be solved by rearranging a bit more.

Fix Issue #241 - Minimap draws over Status Bar

---

src/savepng.cpp
src/savepng.hpp

Previously, SDL_SavePNG would crash if the file could not be opened.

SDL_SavePNG: fail softly

---

src/interface/identify_and_appraise.cpp
src/interface/interface.hpp
src/magic/castSpell.cpp
src/net.cpp

This is a fix for #48.
The issue is that there was never a packet implemented to handle opening the GUI. All of the functionality already existed and works, but nothing ever called the GUI on the Client. Packet 'CRCU' was added to fix this.
Additionally, a function was added 'CloseIdentifyGUI()' to improve consistency. This is a temporary fix until #177 is fixed.

Fix Issue #48 - Client Remove Curse Spell does not open GUI

---

src/cppfuncs.hpp
src/files.cpp
src/files.hpp
src/init.cpp
src/init_game.cpp

This has several benefits, especially with regard to support for
alternative data directories:
- Supports datadir without trailing slash for player name lists
- Fixes #307
- Reduces assumptions about datadir outside files.cpp

getLinesFromFile -> getLinesFromDataFile

---

src/interface/identify_and_appraise.cpp
src/interface/interface.hpp
src/item_usage_funcs.cpp
src/magic/castSpell.cpp
src/net.cpp

This is an enhancement to the Identify and Remove Curse Scrolls to make them use the preexisting GUI, rather than using custom logic (random logic).
Note: This is a simple change, it does not change any existing logic to cursed scrolls, or add anything. It will still use the scroll even if there is nothing to Identify or Uncurse. It will still use the Scroll even if they close the GUI before selecting.

Enhancement - Identify & Remove Curse Scrolls use GUI

---

CMakeLists.txt
src/editor.cpp
src/game.cpp
src/main.cpp
src/main.hpp

I started to work on packaging barony for *BSD systems thus the need to be able to install them properly with the help of the handy GNUInstallDir plugin, possibility to rename editor binary to avoid possible conflicts. I did not apply purposely for Darwin machines as I  was not sure @addictgamer would like (probably on these, only GOG and Steam are planned ... not home-brew/MacPorts ?).

Cmake clean up

---

lang/en.txt
src/interface/drawminimap.cpp
src/item_usage_funcs.cpp

* Use iterator instead of const_iterator in minimapPing.erase(it) to fix Linux compilations under older C++ standards

* Fix lang file clash + Linux VM build

---

src/interface/interface.hpp

by using memset(interactText, 0, 128) to init char array.

* Fix warning in FollowerRadialMenu constructor and fix compilation on Ubuntu 14.04

---

src/menu.cpp

The datadir could be unmounted thus leading to crash
when trying to load levels later on.

Fix crash startup.

---

src/sound.cpp

After Save & Quit, openal lib aborts due to
further locking failure.

Fix openal locking state failure.

---

lang/en.txt
src/actboulder.cpp
src/collision.cpp
src/files.cpp
src/game.cpp
src/game.hpp
src/interface/consolecommand.cpp
src/interface/drawstatus.cpp
src/interface/interface.cpp
src/interface/interface.hpp
src/interface/updatecharactersheet.cpp
src/main.cpp
src/main.hpp
src/maps.cpp
src/menu.cpp
src/menu.hpp

+ Add mute audio option if window focus lost
+ Add option to show skills as 20 / 100 instead of basic, adept, master etc.
* Fix steam leaderboard display for >15 entries
* Fix camera turn up/down/left/right getting rebound if set to defaults
* Fix boulders spawning ontop of chests/doors etc AGAIN. But this time for sure. Removes the trapdoors for the trap, and no trapdoor = no boulder. 
* Boulders now smoosh furniture instead of rolling through em.
* Show brawlermode status on enabling the command (let's you know if broken already)
* Fix furniture ghost hp displaying incorrectly sometimes when swapping targets
* minotaur/hunger icons move when resizing hp/mp bar scales.

* v3.2.2 Further tile bucket optimizations

---

src/entity.cpp
src/menu.cpp

* Fix using 'use last character' setting the savefile incorrectly and deleting the first slot always.

* Fix random crashing due to traps on borders of map

---

LICENSE.txt
VS.2015/Barony/Barony.vcxproj.filters
src/json.cpp
src/json.hpp

Adds files to read/write json to/from classes and structs. Process is pretty simple, there's an example in json.hpp:
```
class ExampleClass {
private:
Uint32 MyNumber;
String MyString;
public:
// defines how to read/write the file to json:
void serialize(FileInterface * file) {
file->property("MyNumber", MyNumber);
file->property("MyString", MyString);
}
};
```
Then when you want to read a file into an object:
```
// read an object from a json file:
ExampleClass exampleObject;
FileHelper::readObject("myJsonFile.json", exampleObject);
```
Or write a file from an object:
```
// write an object to a json file:
ExampleClass exampleObject;
FileHelper::writeObject("myJsonFile.json", EFileFormat::Json, exampleObject);
```
The benefits of this are huge. JSON is a standard and widely popular …

JSON file reader/writer

---

src/menu.cpp

- Removed call to SDL_WarpMouseInWindow() which causes the mouse to be set back to the last tab clicked on when hitting the accept button in the options menu.

Fix mouse being reset to tab after hitting accept in setting menu.

---

VS.2015/Barony/Barony.vcxproj
VS.2015/Barony/Barony.vcxproj.filters
src/UnicodeDecoder.h
src/game.cpp

A fix for #378 .
**Added:**
+ Added UnicodeDecoder.h as a utility header to handle parsing UTF8.
**Modified:**
* Fixed backspacing UTF8 characters requiring two backspaces to clear the character.
Based off the answer here: https://stackoverflow.com/a/22135005/8552466
Using modified code by Bjoern Hoermann (which was then further modified), following his license requirements found here: http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
Checks to see if the character to be removed is UTF8 or not. If it is, remove two characters.
If it's not UTF8, proceed as normal.

Fix UTF8 characters requiring two backspaces

---

src/game.cpp

Navigating through sub directories is related to Mac applications
structure only.

Fix barony binary loading content.

---

src/ui/Button.cpp
src/ui/Field.cpp
src/ui/Frame.cpp
src/ui/Slider.cpp

Really simple PR that scales UI elements graphically from the virtual screen dimensions (1080p) to the real screen dimensions.
Check that I didn't mix any usage of xres/yres up! Some x + width / y + height properties are combined inline during scaling.

UI elements scaled from virtual screen size to actual screen size

---

src/sound.hpp

This fixes a crash in hamlet when using a binary compiled for OpenAL that is caused by the `NUMMINESMUSIC` being different in OpenAL to FMOD ([the fmod constant is here](https://github.com/TurningWheel/Barony/blob/master/src/sound.hpp#L55)).
I also checked the other constants, and `NUMSWAMPMUSIC` is also wrong, but this doesn't lead to a segfault as the track just winds up unused instead. I've fixed this one as well so that the track can play when randomly chosen.

Fix OpenAL segfault in hamlet

---

.github/workflows/build-linux_fmod_steam.yml
.github/workflows/build-linux_fmod_steam_eos.yml

Updates the `actions/checkout` action used in the GitHub Actions workflows to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.5.2
> - Fix api endpoint for GHES
>
> ## v3.5.1
> - [Fix slow checkout on Windows
>
> ## v3.5.0
> - Add new public key for known_hosts
>
> ## v3.4.0
> - Upgrade codeql actions to v2
> - Upgrade dependencies
> - Upgrade @actions/io
>
> ## v3.3.0
> - Implement branch list using callbacks from exec function
> - Add in explicit reference to private checkout options
> - Fix comment typos
>
> ## v3.2.0
> - Add GitHub Action to perform release
> - Fix status badge
> - Replace datadog/squid with ubuntu/squid Docker image
> - Wrap pipeline commands for submoduleForeach in quotes
> - Update @actions/io to 1.1.2
> - …

update actions/checkout in GitHub Actions workflows to v3

---

.github/workflows/build-linux_fmod_steam.yml
.github/workflows/build-linux_fmod_steam_eos.yml

Updates the [`actions/upload-artifact`](https://github.com/actions/upload-artifact) action used in the GitHub Actions workflow to its newest major version.
Changes in [actions/upload-artifact](https://github.com/actions/upload-artifact):
> ## v3.1.2
> - Update all `@actions/*` NPM packages to their latest versions
> - Update all dev dependencies to their most recent versions
>
> ## v3.1.1
> - Update actions/core package to latest version to remove `set-output` deprecation warning
>
> ## v3.1.0
> - Bump @actions/artifact to v1.1.0
>   - Adds checksum headers on artifact upload
>
> ## v3.0.0
>
> - Update default runtime to node16
> - Update package-lock.json file version to 2
Still using v2 of `actions/upload-artifact` will generate some warning like in this run: …

update actions/upload-artifact in GitHub Actions workflows to v3

---

.github/workflows/build-linux_fmod_steam.yml
.github/workflows/build-linux_fmod_steam_eos.yml

Github Actions v3 has been deprecated since January as such I believe you should update it to v4 given how simple it should be, given ever since your actions have been failing ever since.

Update Github Actions to v4
