TurningWheel/Barony

src/entity.cpp

Fixed bug where enemies would not walk through pickaxed walls

---

src/buttons.cpp
src/editor.cpp
src/files.cpp
src/game.cpp
src/init.cpp
src/init_game.cpp
src/main.cpp
src/main.hpp
src/maps.cpp
src/menu.cpp
src/net.cpp
src/sound.cpp

This allows things like passing a different data directory on the
command line, which can be useful for packaging.

Abstract over data dir

---

src/buttons.cpp
src/editor.cpp
src/files.cpp
src/game.cpp
src/init.cpp
src/init_game.cpp
src/main.cpp
src/main.hpp
src/maps.cpp
src/menu.cpp
src/net.cpp
src/sound.cpp

Reverts TurningWheel/Barony#64

Revert "Abstract over data dir"

---

src/menu.cpp
src/menu.hpp

Based on @pwhelan's #60, but fixes the multiple-entry and 0x0 bugs.

Query SDL for resolutions

---

src/menu.cpp
src/menu.hpp

Here is a working implementation of dynamically querying and then showing resolutions in the settings menu. For the moment the biggest problem with the code is that it will leak memory since the list is initialized when the settings menu is shown. Another problem is that I do no sorting on the actual list of resolutions.

[WIP] Dynamically generate resolutions in settings menu

---

src/buttons.cpp
src/editor.cpp
src/files.cpp
src/game.cpp
src/init.cpp
src/init_game.cpp
src/main.cpp
src/main.hpp
src/maps.cpp
src/menu.cpp
src/net.cpp
src/sound.cpp

Data dir next

---

src/book.cpp
src/book.hpp
src/files.cpp
src/init_game.cpp
src/main.hpp

Less code, more efficient sorting. Yay!

Use C++ list for book discovery

---

lang/en.txt
src/acthudweapon.cpp
src/actpowercrystal.cpp
src/buttons.cpp
src/draw.cpp
src/editor.cpp
src/entity.cpp
src/entity.hpp
src/entity_editor.cpp
src/entity_shared.cpp
src/files.cpp
src/game.cpp
src/game.hpp
src/interface/consolecommand.cpp
src/interface/interface.cpp
src/magic/actmagic.cpp
src/main.cpp
src/main.hpp
src/maps.cpp
src/menu.cpp
src/menu.hpp
src/net.cpp

++ fix crossbow rapid fire exploit
++ fix multiplayer games resuming from save game getting de-synced
++ update lang file

Add power crystal, FPS slider, editor bear trap

---

src/init.cpp
src/main.hpp

couple of resource leaks fixes.

Factoring language memory management freeing code and

---

src/actmonster.cpp
src/entity.cpp
src/entity.hpp
src/entity_editor.cpp
src/monster.hpp
src/monster_automaton.cpp
src/monster_goatman.cpp
src/monster_kobold.cpp

* Refactor animation handlers to be part of main monster entity
+ Add 3 spare windups consts for monster attacks
* Fix cloaks not flapping with new walk function

Refactor animation handlers

---

src/actfountain.cpp

[MASTER] Fix Issue #114 - Client fountains do not stop animating 

---

src/actfountain.cpp
src/actplayer.cpp
src/entity.cpp

[MASTER] Fix Issue #102 - Host "On Fire" status does not disappear

---

src/magic/actmagic.cpp

[MASTER] Fix Issue #100 - Client cannot see themselves "On Fire" 

---

src/magic/actmagic.cpp

[MASTER] Fix Issue #128 - Hit by Locking Spell displays wrong message

---

src/magic/actmagic.cpp

[MASTER] Fix Issue #126 - Client is not affected by Slow Spell

---

src/entity.cpp

[MASTER] Fix Issue #130 - Notify Player when they are no longer Slowed

---

src/magic/actmagic.cpp

[MASTER] Fix Issue #127 - Client is not affected by Confuse Spell

---

src/actplayer.cpp

[MASTER] Fix Issue #116 - Head Bobbing when typing

---

src/actplayer.cpp
src/entity.cpp
src/monster_demon.cpp
src/monster_ghoul.cpp
src/monster_gnome.cpp
src/monster_goblin.cpp
src/monster_human.cpp
src/monster_imp.cpp
src/monster_minotaur.cpp
src/monster_rat.cpp
src/monster_scorpion.cpp
src/monster_shopkeeper.cpp
src/monster_slime.cpp
src/monster_spider.cpp
src/monster_succubus.cpp
src/monster_troll.cpp

[MASTER] Fix Issue #151 - Pools of Blood can hide Items

---

src/magic/castSpell.cpp

[MASTER] Fix Issue #129 - Entities can cast spells while Asleep

---

src/magic/actmagic.cpp

[MASTER] Fix Issue #125 - Spell of Opening does not unlock doors

---

src/net.cpp

[MASTER] Fix Issue #115 - Handle Client Disconnect Gracefully

---

src/actmonster.cpp

[MASTER] Fix Issue #182 - Client Devil Position Desync 

---

src/actboulder.cpp

[MASTER] Fix Issue #163 - Client Boulders Position Desync 

---

src/net.cpp

See #111.
New pull request due to @addictgamer requesting one based on v2.0.7 branch. See #104.

[2.0.7] Fix Issue #104 - Client does not add Limb Entities to map 

---

src/item_usage_funcs.cpp
src/magic/castSpell.cpp

[MASTER] Fix Issue #120 - Cure Ailment does not remove Fire on Clients

---

src/interface/drawstatus.cpp

[MASTER] Top border for stat bars

---

src/items.cpp
src/items.hpp

monster_goatman cant's access its symbol.
isRangedWeapon thus not necessary is more a "preventive" fix.

Linkage issue fix, especially isMeleeWeapon is inlined

---

src/items.cpp
src/menu.cpp
src/monster_insectoid.cpp
src/monster_minotaur.cpp
src/monster_vampire.cpp
src/stat_shared.cpp

+ Misc balance.
+ Fix scores from breaking, display new amount of monsters

Steam usernames fix? in lobbies for clients.

---

src/actplayer.cpp
src/entity.hpp
src/game.cpp
src/monster_automaton.cpp
src/monster_cockatrice.cpp
src/monster_crystalgolem.cpp
src/monster_demon.cpp
src/monster_devil.cpp
src/monster_ghoul.cpp
src/monster_gnome.cpp
src/monster_goatman.cpp
src/monster_goblin.cpp
src/monster_human.cpp
src/monster_imp.cpp
src/monster_incubus.cpp
src/monster_insectoid.cpp
src/monster_kobold.cpp
src/monster_lich.cpp
src/monster_minotaur.cpp
src/monster_scarab.cpp
src/monster_scorpion.cpp
src/monster_shadow.cpp
src/monster_shopkeeper.cpp
src/monster_skeleton.cpp
src/monster_spider.cpp
src/monster_succubus.cpp
src/monster_troll.cpp
src/monster_vampire.cpp

Limb dead reckoning fix

---

CONTRIBUTING.md
INSTALL.txt

For an even shorter summary then the short information below:
- Info about Discord channel for contributing
- Added links
- Info about libz used by libpng
- FMOD deprecated (and disabled if not found)
- Link to GL header files

Updated/extended contributing and install information.

---

src/init.cpp

Clean up generateVBOs

---

src/buttons.cpp
src/draw.cpp
src/draw.hpp
src/editor.cpp
src/editor.hpp
src/items_editor.cpp

Sorted filenames (makes finding the map you're looking for so much easier!) and fix crashing when using a different datadir.

Editor improvements

---

src/game.cpp
src/net.cpp
src/net.hpp

Didn't break in testing on my machines, need an extended testing period to make sure there are no side-effects (betas are great for this).

Try something to make steam networking more reliable.

---

lang/en.txt
src/actarrowtrap.cpp
src/actgeneral.cpp
src/actmagictrap.cpp
src/actmonster.cpp
src/actplayer.cpp
src/actpowercrystal.cpp
src/acttorch.cpp
src/collision.cpp
src/entity.cpp
src/interface/consolecommand.cpp
src/interface/identify_and_appraise.cpp
src/magic/actmagic.cpp
src/main.hpp
src/menu.cpp
src/menu.hpp
src/monster_devil.cpp
src/monster_lich.cpp
src/monster_scarab.cpp
src/stat_shared.cpp

Post-beta bugfix #3?

---

src/Config.hpp.in
src/acthudweapon.cpp
src/actmonster.cpp
src/editor.cpp
src/files.cpp
src/game.cpp
src/init.cpp
src/init_game.cpp
src/menu.cpp
src/net.cpp
src/sound.cpp
src/sound.hpp
src/sound_game.cpp
src/stat.cpp
src/stat.hpp
src/stat_editor.hpp
src/stat_shared.cpp

1/ In the editor few messages were too long
2/ SDL2 now define HAVE_FMOD constant, renaming to fit with USE_TREMOR

Sdl2 constant fixes and buffer overflow fix

---

lang/en.txt
src/game.hpp
src/main.hpp
src/monster_goatman.cpp
src/monster_goblin.cpp
src/monster_human.cpp
src/monster_lichfire.cpp
src/monster_lichice.cpp
src/monster_shopkeeper.cpp
src/monster_skeleton.cpp

Adjust lang file to match layout in code. Reserving this PR to pull in Sokoban fix once found..

* Fix gamepad re-binding menu display.

---

src/sound.hpp

Since it s hot fix I aim master this time, it s just forgotten constant for OpenAL.

Forgotten constant for OpenAL case

---

src/game.hpp
src/main.cpp
src/menu.cpp
src/net.cpp

Since it s not an enterprise app, I was "nice" with the lower range :-)

Mp port sanity

---

src/actmonster.cpp
src/actplayer.cpp
src/entity.cpp
src/game.cpp
src/game.hpp
src/init_game.cpp
src/interface/consolecommand.cpp
src/interface/updatecharactersheet.cpp
src/items.cpp
src/magic/magic.cpp
src/menu.cpp
src/net.cpp
src/net.hpp

Improve multiplayer network processing to not impact frame limiter

---

src/menu.cpp
src/scores.cpp

Line 6372 is fix. Rest of changed areas not really changed.
* Modded games can upload to Steam leaderboard

* Fix Linux crash loading game when multiple savefiles present

---

src/actladder.cpp
src/game.cpp
src/game.hpp
src/init.cpp
src/interface/drawminimap.cpp
src/interface/updatecharactersheet.cpp

Need UNIX system calls to be inserted to copy the log.txt file to "logfiles" folder. Try system("cp")?
Expected results:
- Folder "logfiles" gets created in the Barony user data folder /.barony/ on startup. 
- Confirm no error if folder exists on next launch.
- Up to 30 log_timestamp.txt files get copied into the "logfiles" folder once the game closes.
- Confirm no write issues when copying the logs.
- When log files exceed 30, the oldest one is deleted.
- Copied log files should be OK in formatting and properly display contents when editing/viewing.

Log File Archiving

---

VS.2015/Barony/Barony.vcxproj

* forgot remove steam_api.lib from nodrm config

* disable post-build events by default

---

VS.2015/Barony/Barony.vcxproj
VS.2015/editor/editor.vcxproj

* barony_test now is barony.exe

* fix editor not having different config build names

---

src/book.cpp
src/book.hpp

- 
---
- Replaced usage of NULL with nullptr.
- Joined declaration and assignment where possible.
- Swapped C-style casts with C++ casts.
- Fixed unnecessary copy in ranged-based for loop.
- Added const to local variables where possible.
- Replaced an iterator for loop with ranged-based for loop.
- Changed parameters to const where possible.
- Changed TAB_WIDTH from a #define statement to constexpr in unnamed namespace.
- Commented out the unused SPLIT_WORD_IN_TITLE macro.
- Made more parameters const where possible.
---
- Removed an unused variable.
- Removed unreachable code.
- Removed unnecessary header include.
- Commented out the unused, missing formatTitle() function.
- Removed redundant else statement.

Cleaning Code - book.hpp/cpp

---

src/charclass.cpp
src/charclass.hpp

- Added a break statement fixing a few spells not using the correct level requirement.
---
- Replaced NULL with nullptr.
- Replaced traditional for loops with ranged-based for loops.
- Replaced C-style casts with static_cast.
- Fixed signed/unsigned comparison and renamed loop variable to be descriptive.
- Made parameters const where possible.
- Made setCharacterStatsAfterSerialization() const.
- Replaced while(1) with while(true).
---
- Removed unreachable break statements (due to return statements before them).

Cleaning Code - charclass

---

src/book.cpp

Replaced the long switch statement in the isLetter function with a simpler comparison. This works because chars implicitly cast to int types, with values representing their ASCII code. This is easier to read than the way it was before, and requires fewer comparisons to do the same task.

Update isLetter function in book.cpp

---

src/mod_tools.cpp
src/mod_tools.hpp

Fix a few straggling fopen() type code in mod_tools.cpp/mod_tools.hpp

---

src/interface/interface.hpp
src/player.hpp

* fix hotbar_t constructor?

---

CMakeLists.txt
src/main.hpp

Related to #457, all that was left was cleaning up some dangling references.

Finalize removal of GLUT

---

src/book.cpp
src/editor.cpp
src/game.cpp
src/init.cpp
src/init.hpp
src/init_game.cpp
src/input.cpp
src/input.hpp
src/interface/bookgui.cpp
src/interface/consolecommand.cpp
src/interface/playerinventory.cpp
src/menu.cpp
src/menu.hpp
src/opengl.cpp
src/ui/Button.cpp
src/ui/Button.hpp
src/ui/Field.cpp
src/ui/Field.hpp
src/ui/Frame.cpp
src/ui/Frame.hpp
src/ui/GameUI.cpp
src/ui/MainMenu.cpp
src/ui/MainMenu.hpp
src/ui/Slider.cpp
src/ui/Slider.hpp
src/ui/Text.cpp
src/ui/Text.hpp
src/ui/Widget.cpp
src/ui/Widget.hpp

Quick change-list:
- Implemented pause menu
- Added quit game prompt, disconnect prompt, restart game, end-life, etc.
- 100% Settings menu (Changing video mode works, and Minimap, Messages, and input Binding menus are all functional)
- UI engine changes: draw() functions are now const, and Text can now have a unique outline color

finish-settings

---

src/menu.cpp

Looks like an issue from the temporary interaction of the old menu code and the new menu code.

Fixed a crash on game restart after death.

---

src/interface/consolecommand.cpp
src/interface/consolecommand.hpp

ConsoleVariable is now a template class. Makes it more efficient for exposing data for different types.

Upgrade ConsoleVariable

---

CMakeLists.txt
src/actplayer.cpp
src/charclass.hpp
src/eos.cpp
src/eos.hpp
src/game.cpp
src/init.cpp
src/input.cpp
src/input.hpp
src/interface/bookgui.cpp
src/interface/playerinventory.cpp
src/json.cpp
src/json.hpp
src/ui/Button.cpp
src/ui/Field.cpp
src/ui/Field.hpp
src/ui/Frame.cpp
src/ui/GameUI.cpp
src/ui/MainMenu.cpp
src/ui/Slider.cpp
src/ui/Widget.cpp
src/ui/Widget.hpp

A bunch of small tiny fixes. Check commits

More stuff

---

src/actgeneral.cpp
src/interface/playerinventory.cpp

* fix wrong params in AddItemToChest

---

src/acthudweapon.cpp
src/acttorch.cpp
src/entity.cpp
src/interface/drawstatus.cpp
src/interface/interface.cpp
src/interface/playerinventory.cpp
src/monster_gnome.cpp
src/monster_kobold.cpp
src/monster_shadow.cpp
src/monster_shopkeeper.cpp
src/ui/GameUI.cpp

* gameui button states
* Feather longer scrollbar on keyboard, feather item tooltip show charge % in title
* splitscreen hp bars stop duplicating bars if exist for another player

Couple tweaks

---

src/actgeneral.cpp
src/actplayer.cpp
src/draw.cpp
src/editor.cpp
src/game.cpp
src/input.cpp
src/input.hpp
src/interface/drawstatus.cpp
src/interface/interface.cpp
src/interface/playerinventory.cpp
src/lobbies.cpp
src/main.cpp
src/main.hpp
src/menu.cpp
src/mod_tools.cpp
src/mod_tools.hpp
src/net.cpp
src/player.cpp
src/ui/Field.cpp
src/ui/Frame.cpp
src/ui/GameUI.cpp

use keycodes instead of scancodes

---

src/engine/audio/init_audio.cpp
src/eos.cpp
src/init_game.cpp
src/interface/ui.hpp
src/interface/ui_general.cpp
src/menu.cpp
src/scores.cpp
src/scores.hpp
src/ui/Frame.cpp
src/ui/MainMenu.cpp

Toast notifications

---

src/eos.cpp
src/eos.hpp
src/game.cpp
src/imgui/imgui_impl_opengl3_loader.h
src/init.cpp
src/init_game.cpp
src/interface/ui.hpp
src/interface/ui_general.cpp
src/ui/MainMenu.cpp
src/ui/MainMenu.hpp

merge changes from NX fork

---

src/game.cpp
src/menu.cpp
src/menu.hpp
src/ui/MainMenu.cpp
src/ui/MainMenu.hpp
xcode/Barony/Barony/Config.hpp

scrolling through leaderboard takes list selection with it
bindings always have defaults if they aren't found in config file
save and quit no longer also creates highscore
minotaur maze properly shows save file image

some fixes

---

src/eos.cpp
src/eos.hpp
src/eos_editor.cpp
src/game.cpp
src/game.hpp
src/lobbies.cpp
src/net.cpp
src/steam.cpp
src/ui/LoadingScreen.cpp
src/ui/MainMenu.cpp
src/ui/MainMenu.hpp

friends-only default for lobbies (eos and steam)
enter/return always works to activate console
fix flicker on game start
update game version to 4.0.0
update lobby error messages
menu prompts can rescue focus if it is lost

NX fork changes:

---

src/actwallbuster.cpp
src/files.cpp

* generate path for wall builder

---

src/acthudweapon.cpp
src/actmonster.cpp
src/actplayer.cpp
src/engine/audio/sound.hpp

Fix a few typos, no functional changes.

fix a few typos

---

src/scores.cpp
src/ui/MainMenu.cpp

* warning prompt for unmodded/modded save file loading when you are in the wrong modded state

* modded savefile names are same as regular ones

---

src/actplayer.cpp
src/draw.cpp
src/draw.hpp
src/init.cpp
src/interface/drawstatus.cpp
src/interface/playerinventory.cpp
src/main.hpp
src/opengl.cpp
src/player.cpp
src/ui/GameUI.cpp
src/ui/MainMenu.cpp

- separate FOV for view models
- fix unbinding not always working correctly
- fix control options not working for clients
- fix unbound controls coming back on restart
- fix unable to disable race abilities
- user can change texture size atlas with /tile_texture_size

skr 4.0.1 fixes

---

lang/en.txt
src/engine/audio/init_audio.cpp
src/engine/audio/sound.cpp
src/engine/audio/sound.hpp
src/engine/audio/sound_game.cpp
src/ui/MainMenu.cpp

speaker mode can be configured, is saved to config
fixed 3D audio being reversed front-to-back

Fix surround sound, can configure speaker arrangement in settings
